name = "Easy Show Tool"
id = "EasyShowTool"
maintainer = "Atticus, AIGODLIKE Community"
version = "0.4.0"
tagline = "Adds notes to your node editor"
blender_version_min = "4.2.0"
blender_version_max = "4.3.0"
type = "add-on"
schema_version = "1.0.0"
tags = ["Node","User Interface"]
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/atticus-lv/EasyShowTool"
