name = "Easy Show Tool"
id = "EasyShowTool"
maintainer = "Atticus, AIGODLIKE Community"
version = "0.1.2"
tagline = "Adds notes to your node editor"
blender_version_min = "4.2.0"
type = "add-on"
schema_version = "1.0.0"
tags = ["NODE","INTERFACE"]
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/atticus-lv/"
