name = "Easy Node Notes"
id = "EasyNodeNotes"
maintainer = "Atticus"
version = "0.0.1"
tagline = "Adds notes to your node editor"
blender_version_min = "4.2.0"
type = "add-on"
schema_version = "1.0.0"
tags = ["NODE"]
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/atticus-lv/"
